frase = "   Exercícios de Strings   "
print(frase)
# print(frase[4])
# print(frase[4:14])
# print(frase[:14])
# print(frase[3:])
# print(frase[2:14:2])
# print(frase.count('e'))
# print(frase.upper().count('E'))
# print(frase.lower().count('e'))
# print(len(frase))
# print(len(frase.strip()))
# print(frase.replace('Exercícios', 'Atividades'))
# print('Strings' in frase)